In [68]:
# wrong
import numpy as np
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [69]:
data=unpickle('data_batch_1')

In [137]:
X=data[b'data']
Y=data[b'labels']
test=X[102][1]
ans=Y[102]
X=X[:100,:1]
Y=Y[:100]
test

151

In [138]:
max=np.max(X,axis=0)
X=X/max
test=test/max
test

array([0.59215686])

In [139]:
theta=np.zeros(shape=(1))
def gradient(x,y,theta):
    for i in range(5000):
        gradient=0
        ptheta=np.dot(x,theta)
        gradient=gradient+np.dot((ptheta-y),x)
        theta=theta-0.5/len(y)*gradient
    return theta

In [140]:
temp=gradient(X,Y,theta)

In [141]:
temp

array([6.63966516])

In [142]:
temp*test

array([3.93172329])

In [143]:
ans

9