In [2]:
import numpy as np
from scipy.stats import multivariate_normal

In [3]:
data=np.genfromtxt("breast-cancer-wisconsin.data",delimiter=',')
data

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

In [214]:
np.shape(data)

(699, 11)

In [215]:
X=data[:,1:10]

In [216]:
X=X.astype(int)

In [181]:
X[0]

array([5, 1, 1, 1, 2, 1, 3, 1, 1])

In [217]:
max=np.max(X,axis=0)

In [218]:
X=X/max

In [219]:
Y=data[:,10]

In [104]:
n

4.0

In [185]:
max

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [186]:
np.max(X)

1.0

In [220]:
one=[]
zero=[]
one.append(X[0])
for i in range(len(X)):
    if Y[i]==2.0:
        one.append(X[i])
    elif Y[i]==4.0:
        zero.append(X[i])

In [188]:
np.shape(zero)

(241, 9)

In [221]:
mean1=np.mean(one,axis=0)
mean0=np.mean(zero,axis=0)

In [222]:
np.max(one)

1.0

In [223]:
var1=np.dot((one-mean1).T,one-mean)
var0=np.dot(np.transpose(zero-mean0),zero-mean0)

In [198]:
np.shape(mean0)

(9,)

In [199]:
np.shape(var1)

(9, 9)

In [192]:
var1=var1/np.max(var1,axis=0)
var0=var0/np.max(var0,axis=0)

In [178]:
var1[0]

array([ 4.03803707e-17,  5.35916332e-01,  5.05164014e-01,  4.48109316e-01,
        3.22980662e-01,  2.75662318e-20,  1.96266599e-01,  3.49715160e-01,
       -1.82178010e-18])

In [196]:
print(np.linalg.det(var1))

6.994827488575855e-35


In [224]:
sigma_one=[]
sigma_zero=[]
for i in range(len(X)):
    sigma_one.append(np.exp(np.dot(np.dot((X[i]-mean1),np.linalg.inv(var1)),(X[i]-mean1).T)))
    sigma_zero.append(np.exp(np.dot(np.dot((X[i]-mean0),np.linalg.inv(var0)),(X[i]-mean0).T)))

In [225]:
sigma_one[3]

1.2172194779439165

In [230]:
np.max(var1)

1.1546618441816156e+37

In [203]:
mvn = multivariate_normal(mean0,var0)
mvm = multivariate_normal(mean1,var1)

LinAlgError: singular matrix

In [226]:
y_train=[]
for i in range(len(X)):
    fx0=pdf_multivariate_gauss(X[i],mean0,var0)
    fx1=pdf_multivariate_gauss(X[i],mean1,var1)
    if (fx0>fx1):
        y_train.append(2)
    else:
        y_train.append(4)

5.4204020167935815e-27 6.149892070607425e-25
5.435969417160237e-27 5.896179129429153e-25
5.395310997708843e-27 6.164260859459729e-25
5.412576523608057e-27 5.596109334844222e-25
5.418459374557844e-27 6.136814847397173e-25
5.456652740838522e-27 5.378714110570721e-25
5.3540411015565726e-27 6.156354924492381e-25
5.381313647296007e-27 6.152524835967786e-25
5.313978251178144e-27 5.763538284764769e-25
5.4035643575706376e-27 6.148428234874909e-25
5.3463286636393124e-27 6.146827003721242e-25
5.371726120414143e-27 6.170762287561002e-25
5.459939859069143e-27 6.08996024553449e-25
5.3540411015565726e-27 6.156354924492381e-25
5.44491171427128e-27 5.384573239534703e-25
5.465920421562047e-27 5.943281612682572e-25
5.404933829894046e-27 6.167253013986226e-25
5.4098965668253415e-27 6.159856724040719e-25
5.445736328886159e-27 5.618817815393989e-25
5.4268034526313736e-27 6.134393892992626e-25
5.410816624612093e-27 5.445238700557096e-25
5.427632924672042e-27 5.634220423221688e-25
5.390351581751644e-27 6.171

5.348612536679283e-27 6.1016575948811015e-25
5.349099657158824e-27 6.1641509351021735e-25
5.413145262614632e-27 6.160908936086097e-25
5.349099657158824e-27 6.1641509351021735e-25
5.388995275073237e-27 6.112918399403808e-25
5.3950245288089474e-27 6.162935963944068e-25
5.349099657158824e-27 6.1641509351021735e-25
4.153458749678967e-27 5.939007057864983e-25
5.438952598654889e-27 5.362330430497415e-25
5.426375114909001e-27 6.14447293415153e-25
5.4741089881232816e-27 5.895948223204231e-25
5.423397609117357e-27 5.948934109887176e-25
5.4042386380509896e-27 5.28769576217885e-25
5.349099657158824e-27 6.1641509351021735e-25
5.437410601864021e-27 6.1326703861362425e-25
5.3465896001893524e-27 5.992635253598799e-25
5.415485076980786e-27 6.136492232968767e-25
5.381469861753791e-27 4.921112287576587e-25
5.431585955162786e-27 6.122347781019684e-25
5.419112603668704e-27 6.117845781310706e-25
5.379787347778761e-27 6.165481252043845e-25
5.3890626250777616e-27 5.200757286844737e-25
5.3893921357829384e-27 

In [212]:
y_train

[4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 2,
 2,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 2,
 4,
 4,
 2,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 2,
 4,
 4,
 4,
 2,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 4,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 2,
 2,
 4,
 2,
 2,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,


In [204]:
def pdf_multivariate_gauss(x, mu, cov):
    part1 = 1 / ( ((2* np.pi)**(len(mu)/2)) * (np.linalg.det(cov)**(1/2)) )
    part2 = (-1/2) * ((x-mu).T.dot(np.linalg.inv(cov))).dot((x-mu))
    return float(part1 * np.exp(part2))

In [210]:
Y

array([2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2., 4., 2., 4., 4., 2.,
       2., 4., 2., 4., 4., 2., 4., 2., 4., 2., 2., 2., 2., 2., 2., 4., 2.,
       2., 2., 4., 2., 4., 4., 2., 4., 4., 4., 4., 2., 4., 2., 2., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4., 4., 2., 4., 2., 4.,
       4., 2., 2., 4., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4.,
       4., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 4., 4., 4.,
       2., 4., 4., 4., 4., 4., 2., 4., 2., 4., 4., 4., 2., 2., 2., 4., 2.,
       2., 2., 2., 4., 4., 4., 2., 4., 2., 4., 2., 2., 2., 4., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 4., 2., 2., 4., 2., 4., 4.,
       2., 2., 4., 2., 2., 2., 4., 4., 2., 2., 2., 2., 2., 4., 4., 2., 2.,
       2., 2., 2., 4., 4., 4., 2., 4., 2., 4., 2., 2., 2., 4., 4., 2., 4.,
       4., 4., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 4., 4., 2., 2.,
       2., 4., 4., 2., 2., 2., 4., 4., 2., 4., 4., 4., 2., 2., 4., 2., 2.,
       4., 4., 4., 4., 2.

In [240]:
# import numpy as np
# import math
# class Bayesian(object):
#     def __init__(self,num_train,num_test,num_feat):
#         self.X_train=np.zeros((num_train,num_feat))
#         self.Y_train=np.zeros(num_train)
#         self.X_test=np.zeros((num_test,num_feat))
#         self.Y_test=np.zeros(num_test)
#         self.Y_predicted=np.zeros(num_test)
#         self.num_train=num_train
#         self.num_test=num_test
#         self.num_feat=num_feat
#     def normalization(self):
#         #mins=np.min(self.X_train,axis=0)
#         maxs=np.max(self.X_train,axis=0)
#         #self.X_train = 1 - ((maxs - self.X_train)/maxs-mins)
#         self.X_train=self.X_train/maxs
#         #mins=np.min(self.X_test,axis=0)
#         maxs=np.max(self.X_test,axis=0)
#         #self.X_test = 1 - ((maxs - self.X_test)/maxs-mins)
#         self.X_test=self.X_test/maxs
#         self.Y_train=np.where(self.Y_train==2,0,1)
#         self.Y_test=np.where(self.Y_test==2,0,1)
#     def get_data(self):
#         Data= np.genfromtxt(r'breast-cancer-wisconsin.data', delimiter=',')
#         self.X_train=Data[:self.num_train,:self.num_feat]
#         self.Y_train=Data[:self.num_train,self.num_feat]
#         self.X_test=Data[self.num_train:,:self.num_feat]
#         self.Y_test=Data[self.num_train:,self.num_feat]
#         #self.data_change()
#         self.normalization()
#     def pdf_multivariate_gauss(self,x, mu, cov):
#         part1 = 1 / ( ((2* np.pi)*(len(mu)/2)) * (np.linalg.det(cov)*(1/2)) )
#         part2 = (-1/2) * ((x-mu).T.dot(np.linalg.inv(cov))).dot((x-mu))
#         return float(part1 * np.exp(part2))
#     def class_splitting(self):
#         X_train_1=[]
#         X_train_0=[]
#         for i in range(len(self.Y_train)):
#             if(self.Y_train[i]==1):
#                 X_train_1.append(self.X_train[i])
#             elif(self.Y_train[i]==0):
#                 X_train_0.append(self.X_train[i])
#         self.X_train_1=np.asarray(X_train_1)
#         self.X_train_0=np.asarray(X_train_0)
#     def conditional_densities(self):
#         self.mean_0=np.sum(self.X_train_0,axis=0)/np.shape(self.X_train_0)[0]
#         self.mean_1=np.sum(self.X_train_1,axis=0)/np.shape(self.X_train_1)[0]
#         self.covariance_0=np.dot((self.X_train_0-self.mean_0).T,self.X_train_0-self.mean_0)/np.shape(self.X_train_0)[0]
#         self.covariance_1=np.dot((self.X_train_1-self.mean_1).T,self.X_train_1-self.mean_1)/np.shape(self.X_train_1)[0]
#     def train(self):
#         self.get_data()
#         self.class_splitting()
#         self.conditional_densities()
#     def test(self):
#         j=0
#         p_0=np.shape(self.X_train_0)[0]/np.shape(self.X_train)[0]
#         for i in self.X_test:
#             fx0=self.pdf_multivariate_gauss(i,self.mean_0,self.covariance_0)
#             fx1=self.pdf_multivariate_gauss(i,self.mean_1,self.covariance_1)
#             if(fx0*p_0*.7>fx1*(1-p_0)):
#                 self.Y_predicted[j]=1
#                 j=j+1
#             else:
#                 self.Y_predicted[j]=0
#                 j=j+1
#     def data_change(self):
#         sum_array=[]
#         y=self.X_train.T
#         for i in y:
#             count=0
#             sum=0
#             for j in i:
#                 if(math.isnan(j)):
#                     continue
#                 else:
#                     count=count+1
#                     sum=sum+j
#             sum_array.append(sum/count)
#         for i in range(np.shape(y)[0]):
#             for j in range(np.shape(y)[1]):
#                 if(math.isnan(y[i][j])):
#                     y[i][j]=sum_array[i]
#         self.X_train=y.T
#         y=self.X_test.T
#         for i in range(np.shape(y)[0]):
#             for j in range(np.shape(y)[1]):
#                 if(math.isnan(y[i][j])):
#                     y[i][j]=sum_array[i]
#         self.X_test=y.T
#     def accuracy(self):
#         accuracy=0
#         true_positive=0
#         false_positive=0
#         false_negitive=0
#         print(self.Y_predicted)
#         for i in range(len(self.Y_test)):
#             if(self.Y_test[i]==self.Y_predicted[i]):
#                 accuracy=accuracy+1
#             if(self.Y_test[i]==1 and self.Y_predicted[i]==1):
#                 true_positive=true_positive+1
#             if(self.Y_test[i]==0 and self.Y_predicted[i]==1):
#                 false_positive=false_positive+1
#             if(self.Y_test[i]==1 and self.Y_predicted[i]==0):
#                 false_negitive=false_negitive+1
#         #precision=true_positive/(true_positive+false_positive)
#         #recall=true_positive/(true_positive+false_negitive)
#         print("Accuracy:",accuracy/len(self.Y_test))
#         #print("Precision:",precision)
#         #print("Recall:",recall)
#         #print("F1:",2*precision*recall/(precision+recall))
# def split_data():
#     Data= np.genfromtxt(r'breast-cancer-wisconsin.data', delimiter=',')
#     num_train=int(2*np.shape(Data)[0]/3)
#     num_test=np.shape(Data)[0]-num_train
#     num_feat=np.shape(Data)[1]-1
#     return num_train,num_test,num_feat
# num_train,num_test,num_feat=split_data()
# bay1=Bayesian(num_train,num_test,num_feat)
# bay1.train()
# bay1.test()
# bay1.accuracy()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Accuracy: 0.7682403433476395
